global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.resend.com:587"
  smtp_from: "alerts@aniway.space"
  smtp_auth_username: "resend"
  smtp_auth_password: "re_WKeXb53h_3S5tUGdRH6YEWDHS7FVoaLDx"
  smtp_require_tls: true

route:
  receiver: email-default
  group_by: ['alertname', 'service', 'instance']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 4h
  routes:
    - receiver: telegram-critical
      matchers:
        - severity = "critical"
      continue: true

receivers:
  - name: email-default
    email_configs:
      - to: "rombk2711@gmail.com"
        html: '{{ template "aniway.default.html" . }}'
        headers:
          Subject: "[Aniway][{{ .Status }}] {{ .CommonLabels.alertname }}"
          Reply-To: "alerts@aniway.space"
  - name: telegram-critical
    telegram_configs:
      - bot_token: "8459139354:AAHifX_QVH5q_jzVx0ROs44xD3e2xHKel38"
        chat_id: 801773106
        api_url: https://api.telegram.org
        parse_mode: Markdown
        message: '{{ template "aniway.telegram.message" . }}'
        disable_notifications: false

templates:
  - /etc/alertmanager/templates/*.tmpl
