global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets:
          - localhost:9090

  - job_name: aniway-backend
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: aniway-backend
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_docker_network_name]
        regex: aniway-network|aniway-reload_backend
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: (.+)
        target_label: job
        replacement: $1
        action: replace
      - source_labels: [__meta_docker_container_label_prometheus_metrics_path]
        regex: (.+)
        target_label: __metrics_path__
        replacement: $1
        action: replace
      - source_labels: [__meta_docker_network_ip, __meta_docker_container_label_prometheus_port]
        separator: ":"
        regex: "(.*):(.*)"
        replacement: "$1:$2"
        target_label: __address__
        action: replace
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: instance
        replacement: $1
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_prometheus_instance]
        regex: (.+)
        target_label: component
        replacement: $1

  - job_name: cadvisor
    scrape_interval: 15s
    metrics_path: /metrics
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: cadvisor
        action: keep
      - source_labels: [__meta_docker_network_name]
        regex: monitoring-net|aniway-network
        action: keep
      - source_labels: [__meta_docker_container_name, __meta_docker_container_label_prometheus_port]
        separator: ":"
        regex: "/(.*):(.*)"
        replacement: "$1:$2"
        target_label: __address__
        action: replace
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: instance
        replacement: $1
    metric_relabel_configs:
      - source_labels: [name]
        target_label: service
      - source_labels: [container_label_com_docker_compose_service]
        regex: (.+)
        target_label: service
        replacement: $1

  - job_name: node
    scrape_interval: 15s
    metrics_path: /metrics
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: node
        action: keep
      - source_labels: [__meta_docker_network_name]
        regex: monitoring-net|aniway-network
        action: keep
      - source_labels: [__meta_docker_container_name, __meta_docker_container_label_prometheus_port]
        separator: ":"
        regex: "/(.*):(.*)"
        replacement: "$1:$2"
        target_label: __address__
        action: replace
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: instance
        replacement: $1

  - job_name: postgres-exporters
    scrape_interval: 30s
    metrics_path: /metrics
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: postgres
        action: keep
      - source_labels: [__meta_docker_network_name]
        regex: aniway-network|monitoring-net
        action: keep
      - source_labels: [__meta_docker_container_name, __meta_docker_container_label_prometheus_port]
        separator: ":"
        regex: "/(.*):(.*)"
        replacement: "$1:$2"
        target_label: __address__
        action: replace
      - source_labels: [__meta_docker_container_label_prometheus_instance]
        regex: (.+)
        target_label: instance
        replacement: $1
      - target_label: job
        replacement: postgres
