apiVersion: 1
policies:
  - orgId: 1
    receiver: alertmanager-forward-v2
    groupBy:
      - alertname
      - service
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    muteTimeIntervals: []
