apiVersion: 1
policies:
  - orgId: 1
    receiver: email-default
    groupBy:
      - alertname
      - service
    groupWait: 30s
    groupInterval: 2m
    repeatInterval: 4h
    muteTimeIntervals: []
    routes:
      - receiver: telegram-critical
        matchers:
          - severity = "critical"
        continue: true
